services:
  funasr-online-cpu:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.13
    container_name: funasr-online-cpu
    restart: always
    networks:
      - xiaozhi-network
    privileged: true
    ports:
      - "10096:10095"
    volumes:
      - "./funasr-runtime-resources/models:/workspace/models"
    working_dir: /workspace/FunASR/runtime
    command: bash -c "nohup bash run_server_2pass.sh --download-model-dir /workspace/models --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst --itn-dir thuduj12/fst_itn_zh --hotword /workspace/models/hotwords.txt --certfile 0 > log.txt 2>&1 & tail -f ./log.txt"