services:
  memobase-server-api:
#    image: ghcr.io/memodb-io/memobase:main
    image: registry.cn-shanghai.aliyuncs.com/dapp/xiaozhi:memobase
    container_name: memobase-server-api
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - PROJECT_ID=${PROJECT_ID}
      - API_EXPORT_PORT=${API_EXPORT_PORT}
      - API_HOSTS=${API_HOSTS}
      - USE_CORS=${USE_CORS}
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    ports:
      - "8777:8000"
    networks:
      - xiaozhi-network
    depends_on:
      memobase-server-db:
        condition: service_healthy
      xiaozhi-server-redis:
        condition: service_healthy
    volumes:
      - ./conf/memobase-config.yaml:/app/config.yaml
  memobase-server-db:
    image: registry.cn-shanghai.aliyuncs.com/dapp/xiaozhi:pgvector17
    #image: pgvector/pgvector:pg17
    restart: unless-stopped
    container_name: memobase-server-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    platform: linux/amd64
    #   ports:
    #     - '15432:5432'
    networks:
      - xiaozhi-network
    volumes:
      - ./pgvector_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example -d example"]
      interval: 5s
      timeout: 5s
      retries: 5
  xiaozhi-navidrome:
    image: registry.cn-shanghai.aliyuncs.com/dapp/xiaozhi:navidrome
    #image: deluan/navidrome:0.58.0
    container_name: xiaozhi-navidrome
    restart: always
    env_file:
      - .env
    networks:
      - xiaozhi-network
    ports:
      - "8555:4533"
    volumes:
      - ./navidrome_data:/data:rw
      - ./music:/music:ro
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=
    labels:
      createdBy: "Apps"
  aiproxy:
    image: registry.cn-shanghai.aliyuncs.com/dapp/xiaozhi:aiproxy
    container_name: aiproxy
    env_file:
      - .env
    networks:
      - xiaozhi-network
   # ports:
   #   - "17000:17000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    restart: always
networks:
  xiaozhi-network:
    driver: bridge
